# Generated by Django 3.2.5 on 2022-04-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfood', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
