# Generated by Django 3.2.5 on 2022-04-24 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfood', '0005_auto_20220423_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
