# Generated by Django 3.2.5 on 2022-05-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfood', '0006_rename_ingredients_ingredients_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=2, max_length=70),
            preserve_default=False,
        ),
    ]
