# Generated by Django 3.2.5 on 2022-05-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfood', '0007_auto_20220526_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserApp',
        ),
    ]
