# Generated by Django 3.2.5 on 2022-06-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfood', '0010_recipe_favourites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Recetas',
        ),
    ]
